### ISSUE TITLE
Handle transient CloudWatch errors

### ISSUE THREAD

**Issue by pgieser** [awslabs/amazon-kinesis-scaling-utils#42]
A transient CloudWatch error seems to have triggered the application to shutdown.

Perhaps there is a way to be more tolerant of this kind of error short of shutting down the whole application.

```
19-Aug-2016 16:56:21.863 SEVERE [20] com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.startMonitors Unable to unmarshall error response () (Service: AmazonCloudWatch; Status Code: 500; Error Code: 500 Internal Server Error; Request ID: null)
 java.lang.InterruptedException: Unable to unmarshall error response () (Service: AmazonCloudWatch; Status Code: 500; Error Code: 500 Internal Server Error; Request ID: null)
        at com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.startMonitors(AutoscalingController.java:149)
        at com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.run(AutoscalingController.java:177)
        at java.lang.Thread.run(Thread.java:745)

19-Aug-2016 16:56:21.863 INFO [20] com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.startMonitors Terminating Thread Pool
```

**Comment by IanMeyers** [comment]
Please retest with version .9.5.1. I've added retry on InternalServiceException so should be OK now.

**Comment by pgieser** [comment]
I've deployed this version and will monitor.  Thanks for the quick turnaround!
