### ISSUE TITLE
NPE when down scaling omitted from configuration

### ISSUE THREAD

**Issue by pgieser** [awslabs/amazon-kinesis-scaling-utils#43]
It looks like the initial configuration validation requires minimally an upScaling *or* a downScaling section, but further on there is an assumption that downScaling is present.  (I had omitted the down scaling section from our configuration but then saw this)

```
01-Sep-2016 21:45:23.088 SEVERE [localhost-startStop-1] com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.getInstance null
 java.lang.NullPointerException
	at com.amazonaws.services.kinesis.scaling.auto.AutoscalingConfiguration.validate(AutoscalingConfiguration.java:237)
	at com.amazonaws.services.kinesis.scaling.auto.AutoscalingConfiguration.loadFromURL(AutoscalingConfiguration.java:212)
	at com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.getInstance(AutoscalingController.java:76)
	at com.amazonaws.services.kinesis.scaling.auto.app.KinesisAutoscalingBeanstalkApp.contextInitialized(KinesisAutoscalingBeanstalkApp.java:46)
```

**Comment by IanMeyers** [comment]
Can you please retest this against the latest version? There are guard conditions to prevent NPE's in there and can't see how long ago this was an issue. Not having a scale down is perfectly fine.

**Comment by pgieser** [comment]
I can see that the original code will still throw a NPE:

https://github.com/awslabs/amazon-kinesis-scaling-utils/blob/326e84cd34c4238969018b32cb3f5b00fd7ad256/src/main/java/com/amazonaws/services/kinesis/scaling/auto/AutoscalingConfiguration.java#L240
