### ISSUE TITLE
Error with security token

### ISSUE THREAD

**Issue by pgieser** [awslabs/amazon-kinesis-scaling-utils#46]
Application ran fine for several days, then aborted when this exception started happening: 

```
com.amazonaws.services.kinesis.model.AmazonKinesisException: The security token included in the request is invalid (Service: AmazonKinesis; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: ed73b632-759a-4028-bdf4-968a6a1f5501)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1386)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:939)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:714)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:465)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2023)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:1993)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:711)
```

**Comment by IanMeyers** [comment]
That is a periodic error that usually indicates that your role has been changed or revoked. Can you check whether anything changed in the environment?

**Comment by pgieser** [comment]
I don't think so, since a restart of the application resolved it.  My recollection was that this was around the time of the Dyn DNS attack, so perhaps this was a consequence of an extended network outage.
