### ISSUE TITLE
How to run this without Elastic Beanstalk 

### ISSUE THREAD

**Issue by clemmy** [awslabs/amazon-kinesis-scaling-utils#53]
Hey, I was wondering if anyone can provide some simple instructions on running this on an EC2 instance without Elastic Beanstalk. 

I've downloaded installed Tomcat 7, and successfully deployed the application (I can see the "OK - Kinesis Autoscaling Online"). However, I am unable to get the configuration file url working:

```
com.amazonaws.services.kinesis.scaling.auto.InvalidConfigurationException: Unable to instantiate AutoscalingController without System Property config-file-url
  at com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.getInstance(AutoscalingController.java:84)
  at com.amazonaws.services.kinesis.scaling.auto.app.KinesisAutoscalingBeanstalkApp.contextInitialized(KinesisAutoscalingBeanstalkApp.java:46)
  at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5010)
  at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5504)
  at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
  at org.apache.catalina.core.StandardContext.reload(StandardContext.java:4025)
  at org.apache.catalina.manager.ManagerServlet.reload(ManagerServlet.java:954)
  at org.apache.catalina.manager.HTMLManagerServlet.reload(HTMLManagerServlet.java:633)
  at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:211)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

Not sure if this is the right approach, but I have `export TOMCAT_OPTS="-Dconfig-file-url=<url>"` in my `~/.bashrc`.

**Comment by kazysgurskas** [comment]
I think you want to add it to ```CATALINA_OPTS```, not sure.
For me it was easier to run with jetty-runner and add the process under supervisor, since this is not really a webapp:
```java -Dconfig-file-url=<url> -jar jetty-runner.jar kinesis-scaling-utils.war```

**Comment by nvamshik** [comment]
Hi,
Can you guys help me where should I put - Dlog4j.configuration="C:\svn\shared\java\NetworkTester\cardinal-conf\log4j.properties" in Elastic beanstalk? Also please let me know if I need to upload my log4j.properties file and make changes in it.

**Comment by pgieser** [comment]
We run this in FARGATE and the easiest way to configure it is to put your file in S3.

```
    "environment": [
      {
        "name": "JAVA_OPTS",
        "value": "-Xmx500m -Dconfig-file-url=s3://<your-bucket>/stream-autoscaling-config.json"
      }
    ]
```

**Comment by IanMeyers** [comment]
The project also includes a Dockerfile that includes an optimised Maven build
