### ISSUE TITLE
Readme.md links to corrupted WAR files.

### ISSUE THREAD

**Issue by jotes** [awslabs/amazon-kinesis-scaling-utils#60]
Hi AWS Team,

I tried to deploy your package with Amazon Elastic Beanstalk. I downloaded .war file specific to my region and created a new EB app.

Sadly, app couldn't load. After some digging I saw an exception in logs:
```
27-Sep-2017 16:18:09.839 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1129)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1871)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@6c5a4690]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4969)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5099)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 10 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@2f457ec1]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:135)
	at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:707)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 13 more
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: invalid LOC header (bad signature)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:113)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	... 16 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.IOUtils.readFully(IOUtils.java:65)
	at java.util.jar.JarFile.getBytes(JarFile.java:425)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:111)
	... 17 more

27-Sep-2017 16:18:09.842 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory /var/lib/tomcat8/webapps/ROOT
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:757)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1129)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1871)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

27-Sep-2017 16:18:09.850 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /var/lib/tomcat8/webapps/ROOT has finished in 285 ms
```
That give me some clues -> it looks like one of the `.jar` files are corrupted in your bundles.
I unpacked a war file and executed following commands:
```
ଘ( ᐛ )ଓ ♥ WEB-INF/lib → ls -1 |xargs -n 1 zip -T 
test of aws-java-sdk-cloudwatch-1.11.188.jar OK
test of aws-java-sdk-core-1.11.188.jar OK
test of aws-java-sdk-kinesis-1.11.188.jar OK
warning [aws-java-sdk-kms-1.11.188.jar]:  44875 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  44875
  (attempting to re-compensate)
test of aws-java-sdk-kms-1.11.188.jar FAILED

zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)
test of aws-java-sdk-s3-1.11.188.jar OK
test of aws-java-sdk-sns-1.11.188.jar OK
warning [aws-java-sdk-sqs-1.11.188.jar]:  69300 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  69300
  (attempting to re-compensate)
test of aws-java-sdk-sqs-1.11.188.jar FAILED

zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)
test of commons-codec-1.9.jar OK
test of commons-io-2.5.jar OK
test of commons-logging-1.1.3.jar OK
test of httpclient-4.5.2.jar OK
test of httpcore-4.4.4.jar OK
test of ion-java-1.0.2.jar OK
test of jackson-annotations-2.7.4.jar OK
test of jackson-core-2.6.7.jar OK
test of jackson-databind-2.6.7.1.jar OK
test of jackson-dataformat-cbor-2.6.7.jar OK
test of javatuples-1.2.jar OK
test of jmespath-java-1.11.188.jar OK
test of joda-time-2.2.jar OK
```
Looks like libs for SQS and KMS services are corrupted. After I removed those 2 files from `.war`-bundle, AWS EB  is able to run this app without ZIP error.
Could you update the links in README or upload working `.war` files again?
Thanks in advance,

**Comment by thiagofborn** [comment]
Thanks @jotes 

Just to save you guys some time:

• Download the war (for instance, in case you are near Dublin): 

 ``  wget https://s3.eu-west-1.amazonaws.com/awslabs-code-eu-west-1/KinesisAutoscaling/KinesisAutoscaling-.9.5.5.war  ``  

• Then,  the laziest way to remove those jar files from the war file. 
 ``  zip -d KinesisAutoscaling-.9.5.5.war WEB-INF/lib/aws-java-sdk-kms-1.11.188.jar``
 `` zip -d KinesisAutoscaling-.9.5.5.war WEB-INF/lib/aws-java-sdk-sqs-1.11.188.jar``

• After that, you'll need to re-deploy the KinesisAutoscaling-.9.5.5.war file.

**Comment by IanMeyers** [comment]
Is this an issue with .9.5.8 (latest). I don't believe so and am closing this issue but please re-open if it is.
