### ISSUE TITLE
CloudWatch timeouts crash the service

### ISSUE THREAD

**Issue by tsein-bc** [awslabs/amazon-kinesis-scaling-utils#79]
I'm running 9.5.7 of this service, and I've noticed that sometimes the entire service will crash when a CloudWatch error is thrown:
```
2019-05-15 03:24:57 ERROR AutoscalingController:155 - Unable to execute HTTP request: Connect to monitoring.eu-central-1.amazonaws.com:443 [monitoring.eu-central-1.amazonaws.com/52.94.205.59] failed: connect timed out
java.lang.InterruptedException: Unable to execute HTTP request: Connect to monitoring.eu-central-1.amazonaws.com:443 [monitoring.eu-central-1.amazonaws.com/52.94.205.59] failed: connect timed out
    at com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.startMonitors(AutoscalingController.java:142)
    at com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.run(AutoscalingController.java:170)
    at java.lang.Thread.run(Thread.java:748)
2019-05-15 03:24:57 INFO  AutoscalingController:156 - Terminating Thread Pool
```

**Comment by IanMeyers** [comment]
Closing this - merged PR.
